import { Bootstrap } from '#components/Bootstrap';
import type { Metadata } from 'next';
import { Container } from 'react-bootstrap';

import './globals.css';

export const metadata: Metadata = {
  title: 'Learning Plans',
  description: 'Generated by create next app'
};

type Slots = Readonly<{
  children: React.ReactNode;
  modal?: React.ReactNode;
}>;

export default async function RootLayout({ children }: Slots) {
  return (
    <html lang="en">
      <body>
        <Container className="mt-3">{children}</Container>
        <Bootstrap />
      </body>
    </html>
  );
}
